// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTTAF.API.Data;

namespace UTTAF.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200615045735_NotNullFields")]
    partial class NotNullFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("UTTAF.API.Models.RobotModel", b =>
                {
                    b.Property<Guid>("RobotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataOperation")
                        .HasColumnType("TEXT");

                    b.Property<int>("RobotStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RobotId");

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("UTTAF.Dependencies.Models.AttendeeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("UTTAF.Dependencies.Models.AuthSessionModel", b =>
                {
                    b.Property<string>("SessionReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SessionDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionReference");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
