name: .NET 5 Build

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build API
      run: dotnet build ./GPEEC.UTTAF/UTTAF.API/UTTAF.API.csproj
    
