name: Xamarin.Android

on:
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Wap_Project_Path: GPEEC.UTTAF\UTTAF.Mobile\UTTAF.Mobile.Android\UTTAF.Mobile.Android.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Wap_Project_Path /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
